### ISSUE TITLE
Video Graphics Library (vgl) - Backend for FreeBSD

### ISSUE THREAD

**Issue by osen** [caramelli/higfxback#2]
Hi there,

Your project seems really interesting and is as close to a "digital preservation" Linux distro as I have found so far.

Not quite Linux but FreeBSD has semi-recently moved to kernel modesetting and as such replaced its old syscons (sc) console driver with newcons (vt). In doing so they had to remove support for VGL.

https://www.freebsd.org/cgi/man.cgi?vgl

As you can see by the API documented in this manpage, vgl isn't very large. Does your project have any interest in perhaps creating a compatibility wrapper around this? There are relatively few graphics backends for UNIX-like and as far as I have seen, vgl is fairly nice.

This isn't an "issue" as such, it might just be something cool to consider if it is of interest to you.

**Comment by caramelli** [comment]
Yes, a compatibility wrapper should work. But I am only focusing on
GNU/Linux systems, especially for use on embedded systems.

Nicolas Caramelli

**Comment by osen** [comment]
Yes, this would be entirely for Linux since I don't even think FreeBSD provides a replacement backend for VGL to be wrapped upon (possibly only xorg/X11 remains). Basically it would help in porting FreeBSD vgl based programs to Linux.

That said... I actually don't know of any VGL based software (other than my own hobbiest stuff) that exists to port! I think there was a Quake port once but Linux already has many ports of that!

Anyway, I will close this issue :)
