### ISSUE TITLE
which version of mesa does higfxback require？

### ISSUE THREAD

**Issue by picospuch** [caramelli/higfxback#5]
Great overview about kinds of linux gfx methods!

I'm trying to compile mesa following your slides but there seems no fbdev platform support for the latest mesa, so which version can i use?

**Comment by caramelli** [comment]
Yes, only a wiki is available at the moment to give an overview of the HiGFXback project but it's on my TODO list to clarify all that.
In particular, I currently use a different version of Mesa for each graphics backend. And everything is built by hand as a "Linux from scratch" (a bit like the https://www.linuxfromscratch.org project).
For the Linux Framebuffer graphics backend, the info here on Mesa can probably help: https://github.com/caramelli/yagears/issues/2

It would be nice and easier to have fbdev support in Mesa again, and any help making it is welcome!
